# Generated by Django 5.1.3 on 2025-03-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderTable',
        ),
    ]
