# Generated by Django 5.1.3 on 2025-07-26 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
        ('product', '0003_orderproduct_kitchenorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='kitchenOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='kitchen.kitchenorder'),
        ),
    ]
