# Generated by Django 5.1.3 on 2025-03-04 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_purchaseinvoiceitem_supplier_invoice'),
        ('product', '0004_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ingredients', to='inventory.item')),
                ('order_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_ingredients', to='product.orderproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
