# Generated by Django 5.1.3 on 2025-03-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_orderingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_applied',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=14),
        ),
    ]
