# Generated by Django 5.1.3 on 2025-03-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_order_amount_alter_order_discount_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='vat',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=14),
        ),
    ]
