# Generated by Django 5.1.3 on 2025-03-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_orderproduct_price_alter_orderproduct_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='discount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
    ]
