# Generated by Django 5.1.3 on 2025-07-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenorder',
            name='tables',
            field=models.CharField(blank=True, default=[], null=True),
        ),
    ]
