# Generated by Django 5.1.3 on 2025-09-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_kitchenorder_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenorder',
            name='tables',
            field=models.CharField(blank=True, null=True),
        ),
    ]
