# Generated by Django 5.1.3 on 2025-02-13 10:24

import apps.clients.models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.TextField(blank=True, null=True)),
                ('social_media_links', models.JSONField(blank=True, null=True)),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=apps.clients.models.content_file_name, verbose_name='ClientLogo')),
                ('cover_photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=apps.clients.models.content_cover_name, verbose_name='ClientCoverPhoto')),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('cover_photo_url', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('formation_date', models.DateField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('fcm_url', models.URLField(default='https://fcm.googleapis.com/fcm/send')),
                ('fcm_config', models.JSONField(blank=True, null=True)),
                ('fcm_key', models.TextField(blank=True, null=True)),
                ('user_device_limit_restriction', models.BooleanField(default=False)),
                ('user_device_recognition_restriction', models.BooleanField(default=False)),
                ('approval_needed_for_allowed_devices', models.BooleanField(default=False)),
                ('user_login_allowed_from_multiple_device', models.BooleanField(default=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='clients.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
