# Generated by Django 5.1.3 on 2025-07-26 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('product', '0003_orderproduct_kitchenorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceconsumption',
            name='order_ingredients_consumption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.orderingredients'),
        ),
    ]
