# Generated by Django 5.1.3 on 2025-02-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_branch_supplier_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email_address',
            field=models.EmailField(default='test@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
