# Generated by Django 5.1.3 on 2025-02-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_supplier_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vat',
            field=models.FloatField(default=0.0),
        ),
    ]
