# Generated by Django 5.1.3 on 2025-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_image_item_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='parchageinvoiceitem',
            name='vat',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='final_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
    ]
