# Generated by Django 5.1.3 on 2025-02-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_alert_stock_item_safety_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
