# Generated by Django 5.1.3 on 2025-02-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_supplierinvoice_po_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='waste',
            old_name='total_loss_amount',
            new_name='estimated_cost',
        ),
        migrations.RenameField(
            model_name='waste',
            old_name='note',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='waste',
            name='disposal_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.disposalmethod'),
        ),
        migrations.AddField(
            model_name='waste',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.wastecategory'),
            preserve_default=False,
        ),
    ]
