# Generated by Django 5.1.3 on 2025-02-24 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_disposalmethod_wastecategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waste',
            name='disposal_method',
        ),
        migrations.AddField(
            model_name='waste',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastes', to='inventory.supplierinvoice'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='inventory.wastecategory'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DisposalMethod',
        ),
    ]
