# Generated by Django 5.1.3 on 2025-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
