# Generated by Django 5.1.3 on 2025-03-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_itemcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_stock',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
    ]
