# Generated by Django 5.1.3 on 2025-03-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_item_current_stock_alter_item_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParchageInvoiceItem',
            new_name='PurchaseInvoiceItem',
        ),
    ]
