# Generated by Django 5.1.3 on 2025-03-04 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_purchaseinvoiceitem_supplier_invoice'),
        ('product', '0005_orderingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_ingredients_consumption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.orderingredients')),
                ('purchase_invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseinvoiceitem')),
                ('waste_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.wasteitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
