# Generated by Django 5.1.3 on 2025-03-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_supplierinvoice_final_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_stock',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=14),
        ),
    ]
