# Generated by Django 5.1.3 on 2025-03-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_item_current_stock_alter_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
    ]
