# Generated by Django 5.1.3 on 2025-03-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_wasteitem_loss_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceconsumption',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
    ]
