# Generated by Django 5.1.3 on 2025-03-08 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_invoiceconsumption_quantity'),
        ('product', '0010_alter_orderingredients_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceconsumption',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.order'),
        ),
    ]
