# Generated by Django 5.1.3 on 2025-03-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_purchaseinvoiceitem_supplier_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceconsumption',
            name='order',
        ),
    ]
